In [1]:
import pandas as pd
import numpy as np

In [2]:
%%time
# Load holo system data #
# TxN matrix where T=Number of datapoints and N= number of features 
holodata=pd.read_csv("newdatahead.csv")

CPU times: total: 15.6 ms
Wall time: 50.1 ms

In [3]:
%%time
# Load data #
apodata=pd.read_csv("newdatatail.csv")

CPU times: total: 15.6 ms
Wall time: 17.2 ms

In [4]:
%%time
# Load data #
mergeddata=pd.read_csv("newdatamerged.csv")

CPU times: total: 0 ns
Wall time: 16 ms

In [5]:
# Select those features whose distances fall within a contact threshold in atleast 75% frames of the trajectory #
subset1 = apodata.loc[:, (apodata < 5).sum() >= 0.75 * apodata.shape[0]]
apo_list = subset1.columns.tolist()
print(apo_list)
subset1

['42-61', '42-106', '47-77', '62-96', '64-99', '75-79', '76-79', '76-80', '77-102', '83-148', '83-149', '83-150', '83-152', '90-165', '104-174', '105-165', '107-110', '108-167', '123-299', '123-300', '127-223', '131-255', '156-210', '157-161', '158-214', '159-195', '160-195', '161-173', '161-175', '161-176', '168-297', '172-174', '187-189', '193-239', '194-228', '194-243', '195-218', '195-221', '217-248', '219-255', '229-233', '251-263', '251-264', '256-287', '256-291', '259-284', '298-300', '301-303', '40-53', '47-70', '47-74', '47-179', '48-70', '58-93', '65-70', '66-70', '66-71', '68-72', '69-72', '69-73', '70-74', '111-161', '115-225', '116-218', '121-302', '121-303', '122-301', '122-302', '123-302', '124-126', '124-302', '128-292', '129-294', '132-294', '133-168', '145-154', '145-155', '145-211', '146-151', '146-278', '152-177', '155-177', '161-163', '165-167', '165-168', '165-169', '167-297', '167-298', '168-170', '169-295', '169-296', '174-176', '176-178', '179-183', '180-182', '180-183', '183-185', '184-186', '189-191', '192-194', '192-195', '193-196', '193-240', '197-243', '200-206', '206-210', '208-211', '208-276', '208-277', '228-250', '259-291', '262-287', '288-294', '293-295', 'labels']

,42-61,42-106,47-77,62-96,64-99,75-79,76-79,76-80,77-102,83-148,...,206-210,208-211,208-276,208-277,228-250,259-291,262-287,288-294,293-295,labels
0,3.82132,3.42873,2.84587,4.10261,4.15717,2.85116,2.56359,3.41241,3.56968,2.80351,...,3.23448,3.26659,2.14937,2.37054,4.23288,2.55321,3.73152,3.22434,3.91005,1
1,4.70453,3.91085,2.45441,4.78237,4.39619,3.28716,3.08284,2.78861,4.04778,3.45658,...,3.01885,2.56651,1.68598,1.86528,4.83245,2.79669,3.74043,4.14712,4.03755,1
2,3.84844,3.09659,2.87772,4.14763,5.17373,3.04265,2.63791,2.20654,3.73828,2.99363,...,3.50937,2.55897,1.80969,1.75404,4.97440,4.10110,3.91678,4.17838,3.83324,1
3,4.79277,3.58657,3.16897,3.99015,3.61107,2.52397,3.04125,2.34374,3.60484,4.54984,...,3.19364,2.99045,1.68144,1.97278,3.92667,2.64395,4.40753,4.88757,3.47281,1
4,5.98612,4.36261,2.75447,4.19436,4.04662,2.43568,2.56783,2.29512,3.12514,3.83903,...,3.55552,2.73356,1.66661,1.76805,4.26109,3.04607,3.28184,2.96158,3.32024,1
5,4.60052,3.80121,3.43464,3.21491,4.10416,3.12936,2.22151,2.87004,3.17702,3.61659,...,2.91514,2.17636,1.76456,2.08183,4.71643,2.84921,4.38562,3.52437,3.56246,1
6,4.62388,3.40071,2.81767,3.57242,4.84813,2.74288,3.14748,3.33566,3.42314,3.80279,...,3.19398,2.75131,1.77868,1.94174,4.95506,2.10945,3.63167,3.71942,3.54885,1
7,4.43192,3.87820,2.63754,3.82500,5.60092,2.58820,2.62546,2.72318,3.70228,3.68961,...,3.42912,2.38224,1.61463,2.16107,5.00754,3.35265,4.48437,2.87608,3.76225,1
8,5.42514,3.49887,2.80710,3.89916,4.85450,2.87627,2.57352,2.89458,3.58699,5.61406,...,3.51785,2.77778,1.75556,2.10910,4.91569,2.16458,5.08159,4.75566,4.57949,1
9,4.10683,2.81734,2.65662,3.53604,3.81876,2.44155,3.24985,2.76665,3.87749,5.22366,...,3.18107,2.94085,1.61910,2.02958,4.52376,3.43610,6.17080,3.01491,4.13469,1

In [6]:
# Select those features whose distances fall within a contact threshold in atleast 75% frames of the trajectory #
subset2 = holodata.loc[:, (holodata < 5).sum() >= 0.75 * holodata.shape[0]]
holo_list = subset2.columns.tolist()
print(holo_list)
subset2

['42-61', '42-106', '47-77', '50-104', '53-106', '62-96', '63-77', '64-99', '75-79', '76-79', '76-80', '76-178', '77-102', '77-175', '80-176', '81-89', '81-90', '81-174', '83-152', '89-141', '90-165', '104-174', '105-165', '107-110', '108-167', '113-195', '116-122', '123-300', '124-225', '124-300', '127-223', '131-255', '131-256', '154-161', '156-196', '156-210', '157-161', '158-214', '159-195', '160-195', '161-173', '161-175', '187-189', '191-193', '193-239', '194-228', '194-243', '195-218', '195-221', '197-207', '199-207', '207-274', '208-271', '213-229', '215-259', '217-248', '219-255', '229-233', '232-238', '251-263', '251-264', '256-287', '259-283', '259-284', '297-299', '298-300', '32-55', '39-59', '40-53', '47-70', '47-179', '48-70', '65-70', '66-70', '66-71', '68-72', '69-72', '69-73', '70-74', '87-170', '94-102', '111-161', '114-160', '115-225', '121-302', '122-302', '123-302', '124-126', '124-302', '133-168', '146-278', '152-177', '161-163', '165-167', '165-168', '165-169', '167-297', '167-298', '168-170', '169-295', '169-296', '174-176', '176-178', '180-182', '180-183', '183-185', '184-186', '192-194', '192-195', '193-196', '193-240', '195-228', '197-243', '228-250', 'labels']

,42-61,42-106,47-77,50-104,53-106,62-96,63-77,64-99,75-79,76-79,...,183-185,184-186,192-194,192-195,193-196,193-240,195-228,197-243,228-250,labels
0,4.51334,2.83109,3.73651,2.92703,4.27318,4.45411,3.77693,4.02397,3.00448,2.90591,...,4.35954,4.16953,3.87545,2.42202,2.79482,2.09060,4.68871,4.15235,4.94829,0
1,4.50087,2.40675,3.87865,2.90264,4.05759,4.99264,3.42611,2.73471,2.81554,3.25684,...,4.23091,3.98505,4.16194,2.48269,3.02385,2.16528,3.84523,4.26948,5.00666,0
2,4.11454,2.15821,4.49664,4.66221,4.18573,4.18731,3.81736,4.20195,2.56455,2.86544,...,4.41427,3.80844,3.70233,2.68781,2.50487,2.39629,4.45253,4.13866,4.74125,0
3,4.65797,2.46239,4.84954,4.74151,4.63559,4.18140,3.46000,3.15445,2.70688,3.39992,...,4.04162,4.66063,3.96993,2.58189,2.14713,1.98488,4.73510,4.85596,4.50906,0
4,3.97741,2.91885,3.50209,4.98714,4.07415,4.83855,1.76321,4.52595,2.98691,2.49516,...,3.96283,4.12451,3.53011,2.76082,2.81569,2.33775,4.90827,4.20524,4.58139,0
5,4.79362,2.95501,3.89303,5.00924,4.39812,4.36362,1.99415,3.74618,3.12041,3.07474,...,3.87178,3.95009,4.29807,2.49627,3.02839,2.07575,4.34882,3.93870,4.19337,0
6,4.75037,2.17528,4.40233,4.37476,4.45807,4.34286,1.74372,2.25282,2.87771,2.42763,...,4.06396,3.83149,3.77869,2.34783,2.94293,2.26930,4.86515,3.58051,4.54190,0
7,3.76265,2.50319,3.98255,3.77710,4.38625,4.62458,1.72272,4.47200,2.77919,2.77026,...,4.16646,4.35988,4.06241,3.16043,2.68494,2.00463,4.22815,4.60482,4.39657,0
8,4.29455,3.22367,4.52862,2.35842,4.13708,4.18094,1.66122,3.26638,2.83280,3.31684,...,4.53132,4.18964,3.74769,2.57762,2.45972,2.08043,4.49888,4.29836,4.24012,0
9,3.65747,2.28475,3.78029,2.01497,4.59439,3.17865,1.83234,2.20305,2.64141,2.71913,...,4.32060,4.41036,3.75796,2.54612,2.99118,2.25247,4.55735,4.52807,5.25162,0

In [7]:
# Create a list of all identified edges #
tmp = apo_list + holo_list
totallist = []
[totallist.append(x) for x in tmp if x not in totallist] # Remove duplicates 
print(len(apo_list))
print(len(holo_list))
print(len(totallist))

115
115
148

In [8]:
## FIND UNIQUE EDGES OF APO AND HOLO SYSTEMS ##
uniqueapo = []
[uniqueapo.append(x) for x in apo_list if x not in holo_list]
print(len(uniqueapo))
print(uniqueapo)

uniqueholo = []
[uniqueholo.append(x) for x in holo_list if x not in apo_list]
print(len(uniqueholo))
print(uniqueholo)

uniquelist = uniqueapo + uniqueholo
len(uniquelist)

33
['83-148', '83-149', '83-150', '123-299', '161-176', '168-297', '172-174', '256-291', '301-303', '47-74', '58-93', '116-218', '121-303', '122-301', '128-292', '129-294', '132-294', '145-154', '145-155', '145-211', '146-151', '155-177', '179-183', '189-191', '200-206', '206-210', '208-211', '208-276', '208-277', '259-291', '262-287', '288-294', '293-295']
33
['50-104', '53-106', '63-77', '76-178', '77-175', '80-176', '81-89', '81-90', '81-174', '89-141', '113-195', '116-122', '124-225', '124-300', '131-256', '154-161', '156-196', '191-193', '197-207', '199-207', '207-274', '208-271', '213-229', '215-259', '232-238', '259-283', '297-299', '32-55', '39-59', '87-170', '94-102', '114-160', '195-228']

66

In [9]:
# Remove features = distances between two adjacent residues #
new_list = []
count=0
diff=[]
for x in uniquelist:
    first, second = x.split('-')
    if abs(int(first) - int(second)) == 1:
        count+=1
        uniquelist.remove(x)
        new_list.append(x)
print(count)
print(new_list)
print(len(uniquelist))

0
[]
66

In [10]:
# Select features and labels #
features = mergeddata[uniquelist]
target = mergeddata['labels']
# Combine features and target into a single DataFrame
df_to_save = pd.concat([features, target], axis=1)
# Save to CSV file
df_to_save.to_csv("merged.csv", index=False)
df_to_save.head()

,83-148,83-149,83-150,123-299,161-176,168-297,172-174,256-291,301-303,47-74,...,232-238,259-283,297-299,32-55,39-59,87-170,94-102,114-160,195-228,labels
0,6.98172,8.03743,8.49984,4.84695,4.78105,5.04026,4.63637,14.2376,5.40775,5.61842,...,5.11529,2.26574,2.96213,4.96796,4.80872,3.29250,3.56276,4.62672,4.68871,0
1,7.91593,8.46268,9.79619,5.72662,4.99733,5.13205,4.36940,15.1991,4.97206,4.99449,...,3.16481,2.94757,2.90008,4.80238,3.67042,4.25556,4.81380,4.41905,3.84523,0
2,3.19709,4.14582,5.59771,4.29520,4.94506,5.21529,5.01088,14.4558,5.07030,5.63425,...,3.12993,1.96796,2.89515,5.51889,3.78153,4.38807,4.91285,4.38986,4.45253,0
3,4.92428,2.19683,5.15414,5.15719,4.69634,5.01173,5.00048,14.3499,4.94101,5.54568,...,2.78793,2.65412,4.95467,4.73967,3.51232,4.20944,3.97991,4.85550,4.73510,0
4,3.36984,3.98278,5.10306,3.88632,5.00283,5.11213,4.98825,14.5466,5.37213,5.62442,...,2.30889,2.13422,2.96693,3.69179,4.22143,4.78941,4.54001,4.96115,4.90827,0